### ISSUE TITLE
request for Android Smell catalog

### ISSUE THREAD

**Issue by hhhwwwuuu** [jreimone/refactory#1]
hi,
I know this repository when I read the paper.
I am working on the Code smells detection in Android App.
Hence, I try to collect related information about smell catalogue from (www.modelrefactoring.org/smell_catalog/)
But, this link is unable to access. 
Is there another web or paper to read for leaning Android smells?

Thanks in advance

**Comment by jreimone** [comment]
Very late addition @hhhwwwuuu you can find the compiled catalog here, too: https://martinbrylski.github.io/android_smells/
